export const t = {
  site: {
    title: 'Posjeti Bužim – Vikend kuće',
    description:
      'Pregledajte vikend kuće s bazenima u Buzimu. Kontaktirajte vlasnike direktno za rezervaciju.',
  },
  home: {
    heading: 'Posjeti Bužim',
    subtitle:
      'Otkrijte mir prirode i uživajte u odmoru u jednoj od naših vikendica sa bazenom — okruženi zelenilom i gostoljubivošću malog bosanskog grada.',
    empty: 'Trenutno nema dostupnih oglasa.',
    listingsHeading: 'Izdvojene vikendice',
    aboutTitle: 'O Bužimu',
    aboutP1:
      'Bužim je manji grad smješten u Unsko-sanskom kantonu, poznat po svojoj staroj tvrđavi koja dominira panoramom mjesta i svjedoči o bogatoj historiji ovog kraja. Okružen zelenim brdima i mirnom prirodom, Bužim nudi pravi bijeg od svakodnevne gužve — idealno mjesto za odmor u prirodi, uz gostoljubivost lokalnog stanovništva.',
    aboutP2:
      'Bilo da tražite mir za porodični odmor ili priliku za istraživanje netaknute prirode Krajine, Bužim vas dočekuje otvorenih ruku.',
    ctaButton: 'Pogledaj vikendice',
  },
  vikendice: {
    pageTitle: 'Vikendice – Posjeti Bužim',
    heading: 'Vikendice',
    empty: 'Trenutno nema izdvojenih vikendica.',
  },
  house: {
    pool: 'Bazen',
    guests: (n: number) => `Do ${n} gostiju`,
    perNight: (price: number) => `${price} KM / noć`,
    about: 'O ovoj kući',
    checkAvailability: 'Provjeri dostupnost',
    howToBook: 'Kako rezervisati',
    howToBookBody:
      'Rezervacija se dogovara direktno s vlasnikom. Kada provjerite da su datumi slobodni, kontaktirajte vlasnika i dogovorite boravak.',
  },
  availability: {
    checkIn: 'Dolazak',
    checkOut: 'Odlazak',
    available: 'Ovi datumi su slobodni! Kontaktirajte vlasnika za rezervaciju.',
    unavailable: 'Nažalost, kuća nije dostupna za odabrane datume.',
    invalid: 'Datum dolaska mora biti prije datuma odlaska.',
  },
  owner: {
    login: 'Prijava',
    signup: 'Registracija',
    email: 'E-mail',
    password: 'Lozinka',
    fullName: 'Ime i prezime',
    phone: 'Telefon',
    loginButton: 'Prijavi se',
    signupButton: 'Registruj se',
    noAccount: 'Nemate nalog?',
    hasAccount: 'Već imate nalog?',
    dashboard: 'Moje vikendice',
    addHouse: 'Dodaj vikendicu',
    editHouse: 'Uredi vikendicu',
    logout: 'Odjava',
    houseName: 'Naziv vikendice',
    description: 'Opis',
    address: 'Adresa',
    maxGuests: 'Maks. gostiju',
    hasPool: 'Ima bazen',
    pricePerNight: 'Cijena po noći (KM)',
    save: 'Sačuvaj',
    published: 'Objavljeno',
    draft: 'Skica',
    photos: 'Slike',
    uploadPhoto: 'Dodaj sliku',
    noFileChosen: 'Slika nije odabrana',
    deletePhoto: 'Obriši',
    noPhotos: 'Još nema slika.',
    edit: 'Uredi',
    confirmDelete: 'Jeste li sigurni da želite obrisati ovu sliku?',
    generateDescription: 'Generiši opis',
    generating: 'Generiše...',
    generateError: 'Greška pri generisanju. Pokušajte ponovo.',
    bookedDates: 'Zauzeti termini',
    addBookedDate: 'Dodaj termin',
    noBookedDates: 'Nema zauzetih termina.',
    dateFrom: 'Od',
    dateTo: 'Do',
    dateNote: 'Napomena (opcionalno)',
    deleteDate: 'Obriši',
    errorLogin: 'Pogrešan e-mail ili lozinka.',
    errorSignup: 'Greška pri registraciji. Pokušajte ponovo.',
    checkEmail: 'Registracija uspješna! Provjerite e-mail za potvrdu.',
  },
}
